In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, KFold
from sklearn.svm import SVR
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.feature_selection import RFE
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np
from sklearn.metrics import mean_absolute_error
import math
from sklearn.preprocessing import StandardScaler
import random
import sklearn
from bayes_opt import BayesianOptimization
from sklearn.metrics import mean_squared_error
import tensorflow as tf

In [2]:
# Step 1: Load your dataset. Make sure you have a CSV file with relevant features and effort (target) column.
# Replace 'your_dataset.csv' with your actual dataset file name and adjust the column names accordingly.
desharnais=pd.read_csv("C:\\Users\\Asus\\Desktop\\Tehran university\\Seminar\\Datasets\\desharnais_dataset.csv",header=None,index_col=0)
columns_desharnais=['TeamExp','ManagerExp','YearEnd','Length','Effort','Transactions','Entities','PointsAdjust','Envergure','PointsNonAjust','Language']
desharnais.set_axis(columns_desharnais,axis='columns',inplace=True)
desharnais.rename_axis("Features", axis=1,inplace=True)
desharnais.rename_axis("Projects", axis=0,inplace=True)
dataset = desharnais

# Step 2: Prepare the data.
X = dataset.drop(columns=['Effort']).values  # Features
y = dataset['Effort'].values  # Target (effort)

seed_value = 42
random.seed(seed_value)
np.random.seed(seed_value)
tf.random.set_seed(seed_value)
# Split data into train and test sets

# Create a classifier
estimator = SVR(kernel='linear')

# Create SFS model
sfs = SequentialFeatureSelector(estimator,n_features_to_select='auto', direction='forward', cv=5 , scoring='neg_mean_absolute_error', tol=0.1)

# Fit SFS model on training data
sfs.fit(X, y)
print(sfs.get_feature_names_out())
# Transform the data to selected features
X_selected = sfs.transform(X)
print(X_selected)

#=====================================================================================================================

num_folds = 5
kf = KFold(n_splits=num_folds, shuffle=True, random_state=seed_value)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_selected)
mean_MAE=[]
mean_MMRE=[]
mean_RMSE=[]
    
for train_index, val_index in kf.split(X_scaled):
    X_train, X_test = X_scaled[train_index], X_scaled[val_index]
    y_train, y_test = y[train_index], y[val_index]
    
    # Step 3: Build the ANN model.
    model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(units=32, activation='relu', input_shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(units=16, activation='relu'),
    tf.keras.layers.Dense(units=1)  # Output layer with a single unit for regression.
    ])

    # Step 4: Compile the model.
    model.compile(optimizer='adam', loss='mean_squared_error')

    # Step 5: Train the model.
    model.fit(X_train, y_train, epochs=5, batch_size=8, verbose=1)

    # Step 6: Evaluate the model.
    y_pred = model.predict(X_test)
    
    mae = mean_absolute_error(y_test, y_pred)
    mean_MAE.append(mae)

    # Calculate Mean Magnitude of Relative Error (MMRE)
    mmre = np.mean(np.abs((y_test - y_pred) / y_test))
    mean_MMRE.append(mmre)

    # Calculate the Root Mean Squared Error (RMSE) to assess the model's performance.
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    mean_RMSE.append(rmse)
    
print(f"Mean Absolute Error mean: {np.mean(mean_MAE)}")   
print(f"Mean Magnitude of Relative Error mean (MMRE): {np.mean(mean_MMRE):.2f}")
print(f"Root Mean Squared Error (RMSE) mean: {np.mean(mean_RMSE)}")

['x3' 'x8' 'x9']
[[  12  302    1]
 [   4  315    1]
 [   1   83    1]
 [   5  303    1]
 [   4  208    1]
 [   4  192    1]
 [   9  145    2]
 [  13  214    1]
 [  12  247    1]
 [   4  103    1]
 [  21  237    1]
 [  17  271    1]
 [   3   88    1]
 [   8  216    1]
 [   9  320    1]
 [   8  152    2]
 [   8  108    1]
 [  14  326    2]
 [  14  340    2]
 [   5   86    1]
 [  12  581    2]
 [  18  255    1]
 [   5  447    1]
 [  20  397    1]
 [   8  283    1]
 [  14  310    1]
 [   6  312    1]
 [  14  491    1]
 [  16  263    1]
 [  14  461    1]
 [   6  190    1]
 [   9  168    3]
 [   9  267    3]
 [   5  285    1]
 [   3  180    3]
 [  17  253    2]
 [  11  351    3]
 [   8  360    1]
 [   4  180    3]
 [  16  523    2]
 [   9  464    1]
 [  34  698    3]
 [  10  106    1]
 [  39  591    1]
 [  18  308    1]
 [  27  424    1]
 [   9  241    1]
 [  11  361    1]
 [   8  103    1]
 [   9  192    1]
 [   7  156    1]
 [   6  131    1]
 [  17  342    1]
 [  12  130    1]
 [  12  155